### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by vizh** [firstrow/logvoyage#15]
Can we join v2 testing/development process?

**Comment by firstrow** [comment]
Hi, sure! I'm almost ready to push code to public repo, but need to finish couple things like docs, to help new users get started and roadmap. So I need for this couple more days.

Thanks.

**Comment by firstrow** [comment]
https://github.com/logvoyage/logvoyage 
sorry, no docs for now, setup is easy, you can write me on irc/gitter if you are interested in contributions on this early stage.
