### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by threeaccents** [firstrow/logvoyage#9]
I'm running `go get github.com/firstrow/logvoyage` and I get this errror `# github.com/firstrow/logvoyage/web/routers/home
../firstrow/logvoyage/web/routers/home/home.go:129: cannot use searchResults (type *goes.Response) as type goes.Response in return argument`

**Comment by firstrow** [comment]
Thanks for report. I will check this out soon.

**Comment by threeaccents** [comment]
@firstrow Thank you

**Comment by threeaccents** [comment]
@firstrow I sent a pull request with the fix

**Comment by firstrow** [comment]
Thank you for PR.
